# -*- coding: utf-8 -*-
"""CNN_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lwD-AcSyi8gmL4hN4MFGMUo0iH2QTHUT
"""

import tensorflow as tf
from tensorflow import keras
import numpy as np

mnist = tf.keras.datasets.mnist

(train_im, train_label), (test_im, test_label) = mnist.load_data()

train_im = train_im / 255.0
train_im = train_im.reshape(60000, 28, 28, 1)
test_im = test_im / 255.0
test_im = test_im.reshape(10000, 28, 28, 1)

model = keras.models.Sequential([
  keras.layers.Conv2D(64, (3,3), activation='relu', input_shape=(28,28,1)),
  keras.layers.MaxPool2D(2,2),
  keras.layers.Conv2D(64, (3,3), activation='relu'),
  keras.layers.MaxPool2D(2,2),
  keras.layers.Flatten(),
  keras.layers.Dense(128, activation='relu'),
  keras.layers.Dense(10, activation='softmax')
])

model.summary()

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(train_im, train_label, epochs=5)

loss, accuracy = model.evaluate(test_im, test_label)

print(loss)
print(accuracy)